### ISSUE TITLE
Roleplay Characters persisting bug

### ISSUE THREAD

**Issue by GroellerKarim** [Ardas-Legends-Development-Team/Ardas-Legends-App#103]
Due to the mapping of RpChars, there is a bug which prevents new rpchars from being created. 

### Issue

The player entity has two fields: 

1. private RpChar rpChar;
2. private Set<RpChar> pastCharacters;

Both of these reference the same column in the RpChar Table which is not possible with JPA. 

### Possible Solution

Instead of having one field for the current rpchar and one for the past chars, we could instead only have a Set of Rpchars in the Player Entity. 

This would require a new field in the RpChar table, which determines whether a rpchar is active or not.

**Comment by Luktronic** [comment]
Done
