### ISSUE TITLE
qol/Movement time needed

### ISSUE THREAD

**Issue by VernonRoche** [Ardas-Legends-Development-Team/Ardas-Legends-App#127]
# Describe the bug or feature
When a player does a movement action he does not know how much time it will take or the path taken. This is also true for the current region card, where we need to show the current movement.

# Describe the solution and what is need to be done
Add an API route to fetch a movement, as well as fix time returned in the POST movement route

**Comment by GroellerKarim** [comment]
Time and Date has been fixed in #134
